package com.meshlit.desktop

data class DesktopDestination(val id: String, val title: String, val description: String, val available: Boolean)
object DesktopDestinations {
    // Names audited against current Android inventory and build 98faaf0. Desktop availability is independent.
    val all = listOf(
        DesktopDestination("engine", "Inference engine", "CPU threads, context, batch/KV options, memory admission and idle unloading", true),
        DesktopDestination("management", "Management dashboards", "All management features grouped by category and type", true),
        DesktopDestination("containers", "Containers and incubator", "Docker/Podman runtime, images and workload isolation · desktop port pending", false),
        DesktopDestination("kubernetes", "Kubernetes management", "Contexts, namespaces, workloads, quotas and reviewed deployments · port pending", false),
        DesktopDestination("terminal", "Terminal", "Built-in human shell commands; optional Ghostty interactive SSH", true),
        DesktopDestination("guardrails", "Response policy and guardrails", "Local system prompt selection; model and provider restrictions remain independent", true),
        DesktopDestination("dolphin", "Dolphin speech and chat", "DataoceanAI speech adapter pending; compatible chat GGUF imports use Models", false),
        DesktopDestination("runners", "Tool runners", "Bounded desktop/server execution and lifecycle management · port pending", false),
        DesktopDestination("discover", "Discover models", "Hugging Face search and revision-pinned verified GGUF downloads", true),
        DesktopDestination("packets", "Packet capture", "Scoped local interface capture with packet and time limits", false),
        DesktopDestination("nodes", "Nodes and devices", "Saved authenticated phone, desktop and cluster API addresses", true),
        DesktopDestination("health", "Device health", "Observed host memory, storage and CPU load", true),
        DesktopDestination("memory", "Memory and storage", "Physical memory, app heap and free disk", true),
        DesktopDestination("tokens", "Token management", "Request output limit and measured usage", true),
        DesktopDestination("search", "Global search", "Search settings, current chat, saved models/devices; optional browser web handoff", true),
        DesktopDestination("appearance", "Appearance", "Saved desktop themes, English/Chinese and font scale", true),
        DesktopDestination("crypto", "Local cryptography", "Offline hashes, random keys, HMAC and authenticated encryption", true),
        DesktopDestination("gibberlink", "GibberLink and English transcript", "Optional foreground agent audio packets with readable text", false),
        DesktopDestination("remotecommands", "Device and cluster commands", "Scoped multi-node chat commands with human and agent switches", false),
        DesktopDestination("p2p", "P2P chat and commands", "Direct phone-to-phone WebRTC with signed pairing and optional TURN", false),
        DesktopDestination("colibri", "Colibri host", "Off/On/Auto routing to an explicitly configured compatible host", true),
        DesktopDestination("models", "Models and downloads", "Import files, manage downloads and load local models", true),
        DesktopDestination("media", "Camera, vision and audio", "Real image input, microphone and existing SDK media paths", false),
        DesktopDestination("configuration", "Configuration profiles", "Export, review and apply portable device settings", false),
        DesktopDestination("personalization", "Memory and personality", "Local recall, profile and bounded self recovery", false),
        DesktopDestination("behavior", "Custom local model behavior", "Custom weights and your own local instructions", true),
        DesktopDestination("recovery", "Checkpoints and recovery", "Encrypted native CPU KV snapshots and honest cluster recovery status", false),
        DesktopDestination("training", "Fine-tuning", "Real Soup LoRA/QLoRA jobs on a paired training host", false),
        DesktopDestination("router", "Model router", "Scenario rules, model chains and answer comparisons", false),
        DesktopDestination("cloud", "Cloud and credentials", "Vendor resources, costs, environments and separate human/agent controls", false),
        DesktopDestination("operations", "Operations dashboard", "Stop this chat request and unload the local process owned by Meshlit", true),
        DesktopDestination("gateway", "Agent Gateway", "Built-in MCP, A2A and model endpoints; content policy", false),
        DesktopDestination("commands", "Commands and instructions", "Human shell commands with bounded output and cancellation", true),
        DesktopDestination("packages", "Lab packages", "Install, list and uninstall packages inside a ready VM", false),
        DesktopDestination("securitylab", "Security Lab", "Scoped assessments and cyber tool companions", false),
        DesktopDestination("providers", "Online providers", "Compatible /v1 and Open WebUI /api hosts; separate service-bound session keys", true),
        DesktopDestination("power", "Power and costs", "Local battery readings when OS reports them; cost accounting pending", true),
        DesktopDestination("external", "External devices and OTG", "USB discovery, permissions and removable storage", false),
        DesktopDestination("acceleration", "Acceleration", "Observed CPU/GPU inventory; accelerator execution qualification pending", true),
        DesktopDestination("agents", "Agent management", "Delegated permissions, real jobs and registered tools", false),
        DesktopDestination("ssh", "SSH nodes and connections", "Pinned outbound SSH and approved-key inbound status", true),
        DesktopDestination("firewall", "Network rules", "Persisted Meshlit listener firewall and network status", false),
        DesktopDestination("device", "Device", "Observed local hardware and process inventory", true),
        DesktopDestination("tasks", "Task manager", "Live local processes, CPU/RSS readings and scoped human Stop", true),
        DesktopDestination("ide", "Code workspace", "User-selected UTF-8 editor, search and Save As; IDE tooling pending", true),
        DesktopDestination("hyperl", "HyperL libraries", "Built-in native CPU recipes and precise sums; separate licence", true),
        DesktopDestination("permissions", "App permissions", "Explicit session grants for selected desktop inference hosts", true),
        DesktopDestination("files", "Files and storage", "User-selected UTF-8 files and Save As; full file/archive management pending", true),
        DesktopDestination("termux", "Termux integration", "Probe an installed shell, manage delegation and view its audit", false),
        DesktopDestination("notifications", "Notifications", "System notification permission and channels", false),
        DesktopDestination("monitor", "Monitoring and layer pipeline", "Live local CPU/RAM charts and process sampling; remote pipeline monitor pending", true),
        DesktopDestination("audit", "Audit and telemetry", "Encrypted audit history, device metrics, OTLP collector and exports", false),
        DesktopDestination("logs", "Logs and export", "Search logs; filter severity and source; export TXT or JSONL", false),
        DesktopDestination("network", "Network and pairing", "Save trusted HTTPS API addresses; discovery and worker enrollment pending", true),
        DesktopDestination("peers", "Forwarding peers", "Manage peers for the existing inference router", false),
        DesktopDestination("runtime", "Linux runtime and sandbox", "VM configuration and agent activation consent", false),
        DesktopDestination("crawler", "Web crawler", "Configure the optional Crawl4AI companion", false),
        DesktopDestination("openclaw", "OpenClaw and autonomy", "Gateway agent, phone model sharing and Android delegation", false),
        DesktopDestination("automation", "Android automation", "Accessibility automation and app allowlists", false),
        DesktopDestination("hooks", "Agent hooks", "Enable and edit user-authored lifecycle scripts", false),
        DesktopDestination("help", "Guide and tutorial", "Desktop connection instructions and implementation boundaries", true),
        DesktopDestination("legal", "Terms and privacy", "Offline policies, accepted version and data controls", true),
        DesktopDestination("about", "About and availability", "Build information and feature implementation status", true),
    )
    fun search(query: String) = all.filter { item -> query.trim().split(Regex("\\s+")).filter { it.isNotBlank() }.all { word -> "${item.title} ${item.description}".contains(word, true) } }
}
