// SPDX-License-Identifier: LicenseRef-HyperL-Community-1.0
// Earlier Apache-2.0 rights remain; see core-hyperl/LICENSE and NOTICE.
package com.meshlit.core.hyperl
/** Source emission is not compilation, device admission or kernel execution. Only
 * elementwise kernels are supported here; reductions require a distinct lowering. */
data class HyperLGeneratedSource(val target:HyperLTarget,val language:String,val source:String,val deviceQualified:Boolean=false)
object HyperLSourceEmitter {
    fun emit(program:HyperLProgram,target:HyperLTarget):HyperLGeneratedSource {
        program.validate();require(program.instructions.none{it.operation=="sum"}){"HyperL reduction lowering unavailable for this target"}
        val language=when(target){HyperLTarget.LLVM_CPU->"C99";HyperLTarget.CUDA->"CUDA C++";HyperLTarget.ROCM_HIP->"HIP C++";HyperLTarget.OPENCL_SPIRV->"OpenCL C source (not SPIR-V binary)";else->error("HyperL source emitter unavailable for $target")}
        val inputs=program.inputs.sorted();val symbols=(inputs+program.instructions.map{it.output}).associateWith{ "v_"+it }
        val qualifier=when(target){HyperLTarget.CUDA,HyperLTarget.ROCM_HIP->"__global__ ";HyperLTarget.OPENCL_SPIRV->"__kernel ";else->""}
        val pointer=if(target==HyperLTarget.OPENCL_SPIRV) "__global " else ""
        val args=inputs.mapIndexed{i,_->"${pointer}const float* input_$i"}+"${pointer}float* result"+"unsigned int n"
        val text=StringBuilder("// Generated by HyperL hyperl/1; elementwise f32 only. No fast-math assumption.\n")
        text.append(qualifier+"void hyperl_kernel("+args.joinToString(", ")+") {\n")
        if(target==HyperLTarget.LLVM_CPU) text.append("  for (unsigned int i = 0; i < n; ++i) {\n")
        else {text.append(if(target==HyperLTarget.OPENCL_SPIRV) "  unsigned int i = get_global_id(0);\n" else "  unsigned int i = blockIdx.x * blockDim.x + threadIdx.x;\n");text.append("  if (i < n) {\n")}
        inputs.forEachIndexed{i,name->text.append("    float ${symbols.getValue(name)} = input_$i[i];\n")}
        program.instructions.forEach{step->val a=symbols.getValue(step.inputs[0]);val expr=when(step.operation){"add"->a+" + "+symbols.getValue(step.inputs[1]);"multiply"->a+" * "+symbols.getValue(step.inputs[1]);"relu"->"($a > 0.0f ? $a : 0.0f)";else->error("Unsupported source operation")};text.append("    float ${symbols.getValue(step.output)} = $expr;\n")
            val value=symbols.getValue(step.output)
            // Preserve observable rejection even when fusion would hide an earlier Inf/NaN.
            val leave=if(target==HyperLTarget.LLVM_CPU) "continue" else "return"
            text.append("    if (!($value <= 3.402823466e+38f && $value >= -3.402823466e+38f)) { result[i] = $value; $leave; }\n")
        }
        text.append("    result[i] = ${symbols.getValue(program.output)};\n  }\n}\n")
        return HyperLGeneratedSource(target,language,text.toString())
    }
}
