#!/usr/bin/env python3
"""Reproduce old/new source inventories. This never promotes source to device proof."""
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OLD = '98faaf0'
BASELINE = '966015b' # First committed structured feature catalog; pre-catalog source was ff0cd771.
MENU = 'app/src/main/kotlin/com/meshlit/ui/modern/SettingsDestinations.kt'

def historic(revision, path):
    return subprocess.check_output(['git','show',f'{revision}:{path}'],cwd=ROOT,text=True)

def menus(source):
    return {m[0]: (m[1],m[2]) for m in re.findall(r'SettingsDestination\("([^"\n]+)"\s*,\s*"([^"\n]+)"\s*,\s*"([^"\n]+)"',source)}

def generate():
    old = menus(historic(OLD,MENU)); current = menus((ROOT/MENU).read_text())
    desktop_text=(ROOT/'desktopApp/src/main/kotlin/com/meshlit/desktop/DesktopDestinations.kt').read_text()
    desktop={m[0]:(m[1],m[2],m[3]=='true') for m in re.findall(r'DesktopDestination\("([^"\n]+)"\s*,\s*"([^"\n]+)"\s*,\s*"([^"\n]+)"\s*,\s*(true|false)\)',desktop_text)}
    catalog=json.loads((ROOT/'docs/feature-map.json').read_text())
    baseline=json.loads(historic(BASELINE,'docs/feature-map.json'))
    before={f['id']:f for f in baseline['features']}
    text=f'''# Android old/new inventory and desktop parity

Generated by `python3 scripts/update-desktop-parity.py` on the current source tree.
Sources: old menu snapshot `{OLD}`, older feature-map baseline `{BASELINE}`,
current Android sources and the working desktop registry. These snapshots are not
an identification of the exact APK first installed on the Samsung; that requires
an artifact hash/version and device record.

**{len(old)} older menu destinations → {len(current)} current menu destinations.**
Current feature-map catalog: **{len(catalog['features'])} feature areas, {len(catalog['operations'])} typed operations**
(the module count in that historical catalog predates the new desktop-only modules).
No percentage of product completeness follows from these counts.

[Full desktop/server requests](DESKTOP_FEATURE_TRACKER.md) · [Build update ledger](DESKTOP_BUILD_LOG.md).

## Menu comparison

Source references: [old/current menu source](../{MENU}),
[modern routing](../app/src/main/kotlin/com/meshlit/ui/modern/ModernSettingsScreen.kt),
[desktop destination registry](../desktopApp/src/main/kotlin/com/meshlit/desktop/DesktopDestinations.kt).
“Desktop source” means the narrower description in that cell, not full Android parity.

| ID / Android menu | Older snapshot | Current Android menu purpose | Desktop source scope / gap |
| --- | --- | --- | --- |
'''
    for id,(title,description) in current.items():
        d=desktop.get(id)
        scope=(('Partial/source: ' if d[2] else 'Port pending: ')+d[1]) if d else 'No desktop destination'
        text+=f'| `{id}` — {title} | {"Present" if id in old else "Added since snapshot"} | {description} | {scope} |\n'
    removed=sorted(set(old)-set(current))
    text+='\nRemoved old menu IDs: '+(', '.join(removed) if removed else 'none.')+'\n'
    text+='''
## Basic/Advanced finding

Modern Android settings stores the mode in `settings-navigation` and filters
`SettingsDestinations.search(query, advanced)`. That filter decides menu visibility;
it does not provide a separate advanced layout within every destination.
`CategoryScreen.categorySections` likewise returns all indexed entries for Advanced
and only non-advanced entries for Simple. A category with no advanced-only entries
can therefore look the same. The V2 category wrapper delegates to that screen.
This source inspection explains a possible cause; no new physical-phone UI test
was performed for this comparison and no Android screen has been changed here.

Desktop now has a curated Basic menu and grouped Advanced menu. Port-pending
items remain explicitly labelled; Basic/Advanced never changes authority.

## Complete current feature-area catalog

Retained statuses below are the **Android catalog's own evidence descriptions**.
They are not new desktop validation. “Baseline” refers to feature ID presence in
the older feature-map, not whether the feature worked on that phone.

| Feature ID / area | Older baseline | Current catalog status | Source references |
| --- | --- | --- | --- |
'''
    for f in catalog['features']:
        links='; '.join(f'[{Path(s).name}](../{s})' for s in f.get('sources',[]))
        status=str(f['status']).replace('|','\\|')
        text+=f"| `{f['id']}` — {f['title']} | {'Present' if f['id'] in before else 'Added since baseline'} | {status} | {links} |\n"
    text+='''
## High-risk parity distinctions

- Android automatic local recovery retries one native text failure after reloading
  the same installed model. Its own UI says it does not repair Android/app code,
  download replacements or retry tools. Full AI/web repair and signed update/rollback
  channels are still catalogued as planned. See [recovery details](desktop/RECOVERY.md).
- Android listener rules gate selected Meshlit listeners. That is not OS-wide
  Windows/macOS/Linux inbound/outbound firewall control.
- Native KV snapshots, manual signed recovery journals and physical multi-phone
  replicated failover are separate mechanisms and evidence gates.
- Android permission, VM, root, accessibility, Termux and USB grants cannot be
  copied into desktop as successful-looking toggles. Desktop needs native adapters.
- Desktop daemon/MCP/agent autonomy is a porting objective; the existing desktop
  CLI's authenticated host requests are not a complete headless server edition.
'''
    return text,old,current

if __name__=='__main__':
    text,old,current=generate()
    assert len(current)==49, 'Review new Android destinations before regenerating parity'
    (ROOT/'docs/ANDROID_DESKTOP_PARITY.md').write_text(text)
    print(f'Wrote parity: {len(old)} old / {len(current)} current menus; source inventory only.')
